# Generated by Django 3.0.6 on 2020-05-15 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_device',
            fields=[
                ('sensor_id', models.IntegerField(db_column='sensor_id', primary_key=True, serialize=False)),
                ('Sensor_name', models.CharField(db_column='sensor_name', max_length=200)),
                ('position', models.CharField(db_column='position', max_length=200)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('gpio', models.IntegerField(db_column='gpio')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_vlaue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(db_column='value')),
                ('measure_date', models.DateTimeField(db_column='measure_date', default=datetime.datetime.now)),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor_device')),
            ],
        ),
    ]
