# Generated by Django 3.0.6 on 2020-05-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('sensors', '0002_sensor_device_home_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_device',
            name='home_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Home'),
        ),
    ]
