# Generated by Django 3.0.6 on 2020-05-15 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home_id', models.IntegerField(db_column='home_id', primary_key=True, serialize=False)),
                ('home_name', models.CharField(db_column='home_name', max_length=200)),
                ('home_location', models.CharField(db_column='location', max_length=500)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('residnet_id', models.AutoField(db_column='resident_id', editable=False, primary_key=True, serialize=False)),
                ('resident_name', models.CharField(db_column='resident_name', max_length=100)),
                ('resident_role', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member'), ('Gust', 'Gust')], db_column='resident_role', max_length=10)),
                ('resident_registered', models.DateTimeField(db_column='resident_registered', default=datetime.datetime.now)),
                ('home_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Home')),
            ],
        ),
    ]
